[package]
name = "peanut_butter"
version = "0.1.0"
authors = ["emilyaherbert <herbert.e@northeastern.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
